### ISSUE TITLE
The backup page occur "Internal Server Error" error

### ISSUE THREAD

**Issue by litianxi** [tkestack/kstone#125]
Steps：
"Cluster Management" -> "Operation" -> "Cluster Feature" -> "Backup: "(open)
Then don't fill in anything, just click the OK button. When I enter the backup page again
The backup page reports an error "Internal Server Error, please check the network or contact the administrator!"
<img width="664" alt="image" src="https://user-images.githubusercontent.com/24453722/164264694-2f1109f0-a8ce-482d-89bf-8d1900f38198.png">

**Comment by tangcong** [comment]
@engow

**Comment by lianghao208** [comment]
Thanks for the report, I think this might be a bug.
It turns on the backup feature without validating the related params. We are suppose to fix this by validating the params in both frontend and backend.

Temporary solution is to turn off the backup feature, after filling in all the params, reopen it.
/cc @engow

**Comment by engow** [comment]
close with kstone-dashboard [pr#11](https://github.com/https://github.com/tkestack/kstone-dashboard/pull/11)
