### ISSUE TITLE
405_error

### ISSUE THREAD

**Issue by xuyandong0822** [tkestack/kstone#126]
以nodeport的方式登录dashboard,导入集群会报这个错误：连接出错(405)!，请检查网络或联系管理员，跪求解！！

**Comment by tangcong** [comment]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/2403673/167244542-8c7750f8-9368-4b4d-b360-b9d17b09e701.png">
please Refer to the installation documentation below
https://github.com/tkestack/kstone/blob/master/docs/installation/kubeadm_en.md

**Comment by jackk01** [comment]
> <img alt="image" width="1032" src="https://user-images.githubusercontent.com/2403673/167244542-8c7750f8-9368-4b4d-b360-b9d17b09e701.png">
> 
> please Refer to the installation documentation below https://github.com/tkestack/kstone/blob/master/docs/installation/kubeadm_en.md



> <img alt="image" width="1032" src="https://user-images.githubusercontent.com/2403673/167244542-8c7750f8-9368-4b4d-b360-b9d17b09e701.png">
> 
> please Refer to the installation documentation below https://github.com/tkestack/kstone/blob/master/docs/installation/kubeadm_en.md

同样遇到这个问题，用 nodeport 访问不行吗？

**Comment by Battlefield-Pony** [comment]
Actually,as my using experience, you can access the kstone through `ingress controller's nodePorts` only, not the `kstone service nodePort`
