### ISSUE TITLE
Is the project still being developed?

### ISSUE THREAD

**Issue by prabhatsharma** [tkestack/kstone#149]
I see last commit in July.

1. Is the project still under active development?
2. Is there a hosted service based on kstone?
3. Is there commercial support?

**Comment by KenSuenobu** [comment]
The problem I see with a project like this is so unnecessary pieces to make it all work.  It should all be a self-contained application rather than having 4 or 5 components to hook together.  I wish you guys luck!

**Comment by tangcong** [comment]
sorry, The past year has been very busy due to other things, and we will start to maintain it soon. @prabhatsharma
