### ISSUE TITLE
deploy kstone dashboard

### ISSUE THREAD

**Issue by fyqls** [tkestack/kstone#3]
I have one etcdcluster only, which is small. Can I just use dashboard to view etcdcluster status.

**Comment by tangcong** [comment]
@fyqls If you want to view the etcdcluster status, you need to deploy at least three components: kstone-dashboard, kstone-api, and kstone-etcdcluster-controller, and then import the cluster to kstone in the console.

**Comment by fyqls** [comment]
3U
