### ISSUE TITLE
Could kstone-dashboard support English UI in future version？

### ISSUE THREAD

**Issue by MinvenX** [tkestack/kstone#35]

**Comment by MinvenX** [comment]
English version UI may attract more developers to participate.

**Comment by tangcong** [comment]
We plan to support it in v0.2.0 at the latest. If anyone can contribute, we can strive for support in v0.1.0.

**Comment by tangcong** [comment]
https://github.com/tkestack/kstone-dashboard/issues/1

**Comment by tangcong** [comment]
https://github.com/tkestack/kstone-dashboard/pull/2

**Comment by tangcong** [comment]
closed with pr https://github.com/tkestack/kstone-dashboard/pull/5
