### ISSUE TITLE
kstone-dashboard issue: Can't change backup parameter

### ISSUE THREAD

**Issue by maudL1n** [tkestack/kstone#38]
In the kstone-dashboard Backup parameter setting page, if I change the BackupIntervalInSecond or MaxBackups or TimeoutInSecond and Click OK, and reopen again, those parameters will revert to the original one.

**Comment by engow** [comment]
https://github.com/tkestack/kstone-dashboard/pull/6

**Comment by engow** [comment]
It has been fixed in [kstone-dashboard](https://github.com/tkestack/kstone-dashboard/pull/6)
