### ISSUE TITLE
Upgrade the CRD version

### ISSUE THREAD

**Issue by jieshiyeskey** [tkestack/kstone#4]
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

k8s versions v1.22.4

**Comment by tangcong** [comment]
k8s 1.22 removes apiextensions.k8s.io/v1beta1 API version, just use apiextensions.k8s.io/v1.
