### ISSUE TITLE
make-mirror-plus有开源计划吗 ？

### ISSUE THREAD

**Issue by demiaowu** [tkestack/kstone#6]
咨询一下，make-mirror-plus有开源计划吗 ？内部好像是etcd-syncer-plus和etcd-syncer-raft

**Comment by tangcong** [comment]
Thank you for your attention to kstone, we currently have a lot of high-priority tasks #2  to do, and make-mirror-plus open source is currently low in priority.

**Comment by demiaowu** [comment]
OK，感谢回复~
