### ISSUE TITLE
helm install error.

### ISSUE THREAD

**Issue by gxjluck** [tkestack/kstone#7]
# helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}

# helm install kstone . -n kstone

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Prometheus.spec): unknown field "probeNamespaceSelector" in com.coreos.monitoring.v1.Prometheus.spec, ValidationError(Prometheus.spec): unknown field "probeSelector" in com.coreos.monitoring.v1.Prometheus.spec, ValidationError(Prometheus.spec): unknown field "shards" in com.coreos.monitoring.v1.Prometheus.spec]

**Comment by tangcong** [comment]
Is prometheus-operator installed in this cluster before? It seems to be a version conflict, please refer to issue #5. It is recommended to use k8s version 1.20, and this cluster does not have prometheus-operator installed.
